import { PropsWithChildren } from "react";
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/navbar/Navbar";
import Providers from "./providers";
import axios from "axios";
axios.defaults.headers.common = {
  Authorization: `Bearer ${process.env.API_KEY}`,
};
axios.defaults.baseURL = process.env.API_URL;

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Samy Bahi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body
        className={`antialiased bg-primary text-secondary text-sm ${inter.className}`}
      >
        <Providers>
          <header className="relative md:sticky top-0 z-20 bg-primary">
            <Navbar></Navbar>
          </header>
          {children}
        </Providers>
      </body>
    </html>
  );
}
